name = "libass_jll"
uuid = "0ac62f75-1d6f-5e53-bd7c-93b484bb37c0"
version = "0.14.0+0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
FreeType2_jll = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
FriBidi_jll = "559328eb-81f9-559d-9380-de523a88c83c"

[compat]
julia = "1.3"
